install:
 - wget https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-all-3.5.1.tar.gz
 - tar -xzvf protobuf-all-3.5.1.tar.gz
 - pushd protobuf-3.5.1 && ./configure --prefix=/usr && make -j8 && sudo make install && popd

language: java

java:
   - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - /usr

