install:
  - wget https://protobuf.googlecode.com/files/protobuf-3.5.1.tar.gz
  - tar -xzvf protobuf-3.5.1.tar.gz
  - pushd protobuf-3.5.1 && ./configure --prefix=/usr && make && sudo make install && popd

language: java

java:
   - oraclejdk8

