package org.einstein.test.proto;


import org.einstein.eproto.api.IEVersion;

import java.util.List;

/**
 * =========================================================
 * +              Auot generated by ethena                 +
 * =========================================================
 *
 * @author Einstein EProto Object Generator(ethena ^_^)
 * ${current_time}
 **/
public interface IEOrderImmutable  extends IEVersion {
    static final int PROTO_CLASS_ID_ = 0;

    
    String getId();
    
    String getDesk();
    
    String getPortfolio();
    
    String getInstrument();
    
    int getQty();
    
    double getPrice();
    
    List<String> getLegs();

}
