package org.einstein.message.eproto.entitys.api;


/**
 * =========================================================
 * +              Auot generated by ethena                 +
 * =========================================================
 *
 * @author Einstein EProto Object Generator
 * 2018-07-05 11:19:59
 **/
public interface IQueryBOImmutable extends org.einstein.eproto.api.ISerializable {
    static final int PROTO_CLASS_ID = 1;
     
    java.lang.String getId();
    
    java.lang.String getDestination();
    
    int getNumber();
}
