package org.einstein.message.eproto.entitys.api;


/**
 * =========================================================
 * +              Auot generated by ethena                 +
 * =========================================================
 *
 * @author Einstein EProto Object Generator(ethena ^_^)
 * 2018-05-22 18:35:22
 **/
public interface IQueryBO extends org.einstein.message.eproto.entitys.api.IQueryBOImmutable {

    
    void setId( java.lang.String  value);
    
    void setDestination( java.lang.String  value);
    
    void setNumber( int  value);
}
