package org.einstein.message.eproto.entitys.api;


/**
 * =========================================================
 * +              Auot generated by ethena                 +
 * =========================================================
 *
 * @author Einstein EProto Object Generator
 * 2018-07-05 11:19:59
 **/
public interface IQueryBO extends org.einstein.message.eproto.entitys.api.IQueryBOImmutable {
     
    void setId( java.lang.String  value);
    
    void setDestination( java.lang.String  value);
    
    void setNumber( int  value);
}
